### ISSUE TITLE
Batch processing

### ISSUE THREAD

**Issue by camjac251** [vyneer/twitchplaylistfixer-rs#1]
Is it possible to input multiple urls in one go with this tool? I was hoping to go through about 300 urls but they need to be manually entered to work.

Could the url be supplied as an argument to the binary? Like `./twitchplaylistfixer-rs https://url/index-dvr.m3u8`

I was hoping to run it like this to run 20 in unison `cat playlist-list-all.txt | xargs -L 1 -P 20 ./twitchplaylistfixer-rs $line`

**Comment by vyneer** [comment]
Done! https://github.com/vyneer/twitchplaylistfixer-rs/commit/baa248596c6e065bf18f43bbc450e5cd34c47511
![render1604065477747](https://user-images.githubusercontent.com/41237021/97712341-5dd93300-1acf-11eb-9e33-b7df40e79bb9.gif)

**Comment by camjac251** [comment]
wow this is incredible. thank you very much
